version: "3.9"
services:
  test:
    image: rust
    command: cargo test
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - postgres-test
    env_file:
      - config.conf

  postgres-test:
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - config.conf


volumes: 
  postgres_test_data: