version: "3.9"
services:
  backend:
    image: rust
    command: cargo run
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "5173:3000"
    depends_on:
      - postgres-local
    env_file:
      - config.conf

  postgres-local:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5454:5432"
    env_file:
      - config.conf

volumes: 
  postgres_data: